config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :users

  resources :live_houses do
  resources :reviews, only: [:index, :create]
end
  get 'live_house_search' => 'live_houses#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/live_house.rb
class LiveHouse < ApplicationRecord
  has_many :reviews, dependent: :destroy

  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

  def self.search(search)
      return selft.all unless search
      LiveHouse.where(['name LIKE ?', "%#{search}%"])
    end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :live_house
  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/live_houses_controller.rb
class LiveHousesController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
    @live_houses = LiveHouse.all
  end

  def show
    @live_house = LiveHouse.find(params[:id])
    @review = Review.new
  end

  def search
   #Viewのformで取得したパラメータをモデルに渡す
   @live_houses = LiveHouse.search(params[:search])
 end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def index
    @live_house = LiveHouse.find(params[:live_house_id])
    @reviews = @live_house.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to live_house_reviews_path(@review.live_house)
    else
      @live_house = LiveHouse.find(params[:id])
      render  "live_house/show"
    end
  end

  def review_params
    params.require(:review).permit(:live_house_id, :score, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def show
     @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user = User.update(user_params)
    redirect_to user_path(@user)
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :profile, :profile_image)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/live_houses_helper.rb
module LiveHousesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<p>検索</p>
<%= form_tag(live_house_search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JamLog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
  <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <% if flash[:notice] %>
  <div class="notification is-info">
    <p class="notice"><%= notice %></p>
  </div>
  <% end %>
  <% if flash[:alert] %>
  <div class="notification is-danger">
    <p class="alert"><%= alert %></p>
  </div>
  <% end %>

  <nav class="navbar is-warning">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-4" style="font-family: cursive;">jamLog</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <% if user_signed_in? %>
    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">

            <p class="control">
              <%= link_to "ライブハウス一覧", live_houses_path, class: " button is-warning is-light" %>
            </p>

            <p class="control">
              <%= link_to "ユーザー一覧", users_path, class: " button is-warning is-light" %>
            </p>

            <p class="control">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <% else %>

    <div id="navbarExampleTransparentExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">

            <p class="control">
              <%= link_to "ライブハウス一覧", live_houses_path, class: " button is-warning is-light" %>
            </p>

            <p class="control">
              <%= link_to "ユーザーー一覧", users_path, class: " button is-warning is-light" %>
            </p>

            <p class="control">
              <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
            </p>
            <p class="control">
              <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
            </p>

          </div>
        </div>
      </div>
    </div>



    <% end %>

  </nav>
  <%= yield %>
</body>
</html>

app/views/live_houses/index.html.erb
<p>店舗名で検索</p>
<%= form_tag(live_house_search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <% @live_houses.each do |live_house| %>
          <div class="card mb-6">
            <header class="card-header">
              <p class="card-header-title">
                <%= live_house.name %>
              </p>
            </header>
            <div class="card-content">
              <div class="content">
                <div class="content average-score">
                  <div class="star-rating mb-2">
                    <div class="star-rating-front" style="width: <%= live_house.review_score_percentage %>%">★★★★★</div>
                    <div class="star-rating-back">★★★★★</div>
                  </div>
                  <div class="average-score-display ml-3 pt-2">
                    <%= live_house.avg_score %>点 <%= live_house.reviews.count %>（件のレビュー）
                  </div>
                </div>
              </div>
            </div>
            <footer class="card-footer">
              <%= link_to live_house_reviews_path(live_house), class: "button card-footer-item" do %>
                レビューを見る
              <% end %>
              <%= link_to live_house_path(live_house), class: "button card-footer-item" do %>
                レビューを書く
              <% end %>
            </footer>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/live_houses/search.html.erb
<p>店舗名で検索</p>
<%= form_tag(live_house_search_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>

<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">


<ul><% @live_houses.each do |live_house| %>
  <div class="card mb-6">
    <header class="card-header">
      <p class="card-header-title">
        <%= live_house.name %>
      </p>
    </header>
    <div class="card-content">
      <div class="content">
        <div class="content average-score">
          <div class="star-rating mb-2">
            <div class="star-rating-front" style="width: <%= live_house.review_score_percentage %>%">★★★★★</div>
            <div class="star-rating-back">★★★★★</div>
          </div>
          <div class="average-score-display ml-3 pt-2">
            <%= live_house.avg_score %>点 <%= live_house.reviews.count %>（件のレビュー）
          </div>
        </div>
      </div>
    </div>
    <footer class="card-footer">
      <%= link_to live_house_reviews_path(live_house), class: "button card-footer-item" do %>
        レビューを見る
      <% end %>
      <%= link_to live_house_path(live_house), class: "button card-footer-item" do %>
        レビューを書く
      <% end %>
    </footer>
  </div>
  <% end %>
</div>
</div>
</div>
</section>

app/views/live_houses/show.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @live_house.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @live_house.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @live_house.avg_score %>点 <%= @live_house.reviews.count %>（件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <%= render 'reviews/form', review: @review, live_house: @live_house %>
      </div>
    </div>
  </div>
</section>

app/views/reviews/_form.html.erb
<p class="is-size-4 mb-3">レビューを書く</p>
<% if review.errors.any? %>
  <div class="notification is-danger">
    <h2><%= review.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="rating-box mt-3">
  <%= form_with model: review, url: live_house_reviews_path(live_house), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
      <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :live_house_id, value: live_house.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <%= link_to "他のレビューを見る", live_house_reviews_path(live_house), class: "button light ml-3 mt-3" %>
  <% end %>
</div>

<%= javascript_pack_tag 'reviews.js' %>

app/views/reviews/index.html.erb
<section class="section mt-6">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card mb-6">
          <header class="card-header">
            <p class="card-header-title">
              <%= @live_house.name %>
            </p>
          </header>
          <div class="card-content">
            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= @live_house.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= @live_house.avg_score %>点 （<%= @live_house.reviews.count %>件のレビュー）
              </div>
            </div>
          </div>
        </div>
        <table class="table is-fullwidth has-text-centered">
          <thead>
            <tr>
              <th>ユーザー</th><th>点数</th><th>内容</th>
            </tr>
          </thead>
          <tbody>
            <% @reviews.each do |review| %>
              <tr>
                <td><%= review.user.username %></td>
                <td><%= review.score %></td>
                <td><%= review.content %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>